/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArquivoInput: typeof import('./src/components/Inputs/ArquivoInput.vue')['default']
    AulaDialog: typeof import('./src/components/Cursos/Etapas/AulaDialog.vue')['default']
    AvaliacaoDialog: typeof import('./src/components/Cursos/Etapas/AvaliacaoDialog.vue')['default']
    AvisoDialog: typeof import('./src/components/AvisoDialog/AvisoDialog.vue')['default']
    base: typeof import('./src/components/Cursos/Cursos base.vue')['default']
    CadastroColaboradores: typeof import('./src/components/Colaboradores/CadastroColaboradores.vue')['default']
    CadastroIndividual: typeof import('./src/components/Colaboradores/FormularioCadastroDialog/CadastroIndividual/CadastroIndividual.vue')['default']
    Card: typeof import('./src/components/Cursos/CursoCard/Card.vue')['default']
    Colaboradores: typeof import('./src/components/Colaboradores/Colaboradores.vue')['default']
    ColaboradoresTabela: typeof import('./src/components/Colaboradores/Tabela/ColaboradoresTabela.vue')['default']
    ComboNoDataInput: typeof import('./src/components/Inputs/ComboNoDataInput.vue')['default']
    ComboSemEncontrarDadosInput: typeof import('./src/components/Inputs/ComboSemEncontrarDadosInput.vue')['default']
    ConfirmarExclusaoDialog: typeof import('./src/components/ConfirmarExclusaoDialog/ConfirmarExclusaoDialog.vue')['default']
    copy: typeof import('./src/components/Dashboard/Dashboard copy.vue')['default']
    CursoCard: typeof import('./src/components/Cursos/CursoCard/CursoCard.vue')['default']
    CursoDetalhe: typeof import('./src/components/CursoDetalhe/CursoDetalhe.vue')['default']
    'CursoDetalhe copy': typeof import('./src/components/CursoDetalhe/CursoDetalhe copy.vue')['default']
    CursoDialog: typeof import('./src/components/Cursos/CursoDialog/CursoDialog.vue')['default']
    CursoLista: typeof import('./src/components/Cursos/CursoLista/CursoLista.vue')['default']
    Cursos: typeof import('./src/components/Cursos/Cursos.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard/Dashboard.vue')['default']
    'Dashboard copy': typeof import('./src/components/Dashboard/Dashboard copy.vue')['default']
    DataInput: typeof import('./src/components/Inputs/DataInput.vue')['default']
    Detalhes: typeof import('./src/components/Colaboradores/Detalhes/Detalhes.vue')['default']
    EtapaAvaliacoes: typeof import('./src/components/Cursos/Etapas/EtapaAvaliacoes.vue')['default']
    EtapaDetalhes: typeof import('./src/components/Cursos/Etapas/EtapaDetalhes.vue')['default']
    EtapaModulos: typeof import('./src/components/Cursos/Etapas/EtapaModulos.vue')['default']
    EtapaRevisao: typeof import('./src/components/Cursos/Etapas/EtapaRevisao.vue')['default']
    FormularioCadastro: typeof import('./src/components/Colaboradores/FormularioCadastro/FormularioCadastro.vue')['default']
    FormularioCadastroDialog: typeof import('./src/components/Colaboradores/FormularioCadastroDialog/FormularioCadastroDialog.vue')['default']
    FormularioDialog: typeof import('./src/components/Colaboradores/FormularioCadastroDialog/FormularioDialog.vue')['default']
    FormularioEdicaoDialog: typeof import('./src/components/Colaboradores/FormularioEdicaoDialog/FormularioEdicaoDialog.vue')['default']
    FormularioFiltroPanel: typeof import('./src/components/Colaboradores/FormularioFiltroPanel/FormularioFiltroPanel.vue')['default']
    HankingGamificacao: typeof import('./src/components/HankingGamificacao/HankingGamificacao.vue')['default']
    HomeComponent: typeof import('./src/components/Home/HomeComponent.vue')['default']
    MeusCursos: typeof import('./src/components/Meus Cursos/MeusCursos.vue')['default']
    ModuloPanel: typeof import('./src/components/Cursos/Etapas/ModuloPanel.vue')['default']
    ParametrosGamificacao: typeof import('./src/components/Parametros/Gamificacao/ParametrosGamificacao.vue')['default']
    PerguntaDialog: typeof import('./src/components/Cursos/Etapas/PerguntaDialog.vue')['default']
    Ranking: typeof import('./src/components/Ranking/Ranking.vue')['default']
    RankingGamificacao: typeof import('./src/components/RankingGamificacao/RankingGamificacao.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./src/components/Inputs/SelectInput.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    Tabela: typeof import('./src/components/Colaboradores/Tabela/Tabela.vue')['default']
    TextoAreaInput: typeof import('./src/components/Inputs/TextoAreaInput.vue')['default']
    TextoInput: typeof import('./src/components/Inputs/TextoInput.vue')['default']
    TopBar: typeof import('./src/components/TopBar/TopBar.vue')['default']
    ValidarCertificado: typeof import('./src/components/certificado/ValidarCertificado/ValidarCertificado.vue')['default']
  }
}
