/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CriarNovaSenha/CriarNovaSenha': RouteRecordInfo<'/CriarNovaSenha/CriarNovaSenha', '/CriarNovaSenha/CriarNovaSenha', Record<never, never>, Record<never, never>>,
    '/Home/Home': RouteRecordInfo<'/Home/Home', '/Home/Home', Record<never, never>, Record<never, never>>,
    '/Login/Login': RouteRecordInfo<'/Login/Login', '/Login/Login', Record<never, never>, Record<never, never>>,
    '/RedefinirSenha/RedefinirSenha': RouteRecordInfo<'/RedefinirSenha/RedefinirSenha', '/RedefinirSenha/RedefinirSenha', Record<never, never>, Record<never, never>>,
  }
}
